// export const meals = [
//   {
//     title: "Homemade Turkish lahmacun",
//     description: "Sometimes called 'Turkish pizza', this crispy flatbread topped with spiced mincemeat is a popular street food across the Middle East",
//     stars: 5,
//     comments: [
//       {
//         username: "Husan",
//         comment: "What an incredible dish, completely convenient for 4-person family!",
//       },
//       {
//         username: "Zeynep",
//         comment: "It was good to prepare a food that you enjoy eating outside at home!",
//       },
//     ],
//     prep: "40 mins",
//     time: "15 mins",
//     difficulity: "Easy",
//     sesrves: 4,
//     nutrition: {
//       kcal: 682,
//       fat: 18,
//       saturates: 6,
//       carbs: 98,
//       sugars: 4,
//       fibre: 6,
//       protein: 40,
//       salt: 2.61,
//     },
//     ingredients: [
//       "3 aubergines",
//       "2 tbsp olive oil, plus extra for brushing",
//       "1 Spanish onion, finely chopped",
//       "2 garlic cloves, crushed",
//       "1 tsp cinnamon",
//       "8 ripe tomatoes, peeled",
//       "small bunch flat-leaf parsley, chopped",
//       "12 lamb chops or cutlets",
//       "paprika, for seasoning",
//       "1 lemon, halved",
//     ],
//     steps: [
//       "Sift the flour into a large bowl, make a well in the middle and sprinkle in the yeast. Pour 125ml water over the yeast, then flick flour over the liquid to create a layer. Cover and leave to rise in a warm place for 15 mins until cracks appear on the surface of that layer.",
//       "Use your hands to mix in 250ml more water along with 1 tsp salt and knead the dough for about 10 mins until elastic and no longer sticky. Add a little more flour if you need to. Cover and leave to rise again in a warm place for 30 mins until doubled in size.",
//       "Heat the oven to as high as it will go (about 240C/220C fan/gas 9) and sprinkle one or two baking trays thinly with cornmeal.",
//       "Pour boiling water from the kettle over the tomatoes, leave to stand briefly, then drain and slip off the skins. Cut the tomatoes in half, cut out the stalks, scoop out the seeds and discard, then chop the flesh.",
//       "Halve the chillies lengthways, cut out the stalks, seeds and white inner membrane, then rinse. Cut lengthwise into fine strips, then crosswise into fine dice.",
//       "Put the tomatoes, chillies, spring onions, finely chopped parsley, beef mince, spices, 1 tsp salt and ½ tsp freshly ground black pepper into a bowl and mix well.",
//       "Take the dough and knead it briefly, then divide into four pieces and shape each into a ball. Roll each ball into a thin circle, place on the prepared baking trays. Spread with a thin layer of the meat mixture.",
//       "Bake each flatbread for 10-15 mins until the edges begin to darken. After removing from the oven, sprinkle the lahmacun with the roughly chopped parsley and sliced onion, then squeeze over a few drops of lemon juice. Serve straightaway.",
//     ]
//   },
//   {
//     title: "Imam Bayildi with BBQ Lamb & Tzatziki",
//     description: "There are hundreds of versions of this Turkish aubergine dish. It is authentically quite oily, but reduce the oil if you prefer.",
//     stars: 4.5,
//     comments: [
//       {
//         username: "Mine",
//         comment: "Made the aubergines as a vegetarian main. Went down very well at a family gathering. Made them the day before and that worked well too. Would definitely make again.",
//       },
//       {
//         username: "Ilkay",
//         comment: "This is really delicious and gets a lot of compliments. I served it with tzatziki and keftas. Not sure why they ask you to cook it until the aubergines 'collapse' - the skins are pretty collapsed after you've chopped out the flesh in step 2. I didn't bother peeling or de-seeding teh tomatoes, but just chopped them up and added them all in at once. It may have been a bit more 'rustic' but it was lovely!",
//       },
//       {
//         username: "Batuhan",
//         comment: "I have cooked this twice and have been really disappointed with the lack of depth of flavour of the aubergine dish Even added a bit of tomato puree to the ripe tomatoes second time around whilst cooking to try to bring out a bit more flavour.",
//       },
//     ],
//     prep: "15 mins",
//     time: "1 hr and 30 mins",
//     difficulity: "Easy",
//     sesrves: 6,
//     nutrition: {
//       kcal: 435,
//       fat: 32,
//       saturates: 14,
//       carbs: 12,
//       sugars: 10,
//       fibre: 5,
//       protein: 27,
//       salt: 5,
//     },
//     ingredients: [
//       "3 aubergines",
//       "2 tbsp olive oil, plus extra for brushing",
//       "1 Spanish onion, finely chopped",
//       "2 garlic cloves, crushed",
//       "1 tsp cinnamon",
//       "8 ripe tomatoes, peeled",
//       "small bunch flat-leaf parsley, chopped",
//       "12 lamb chops or cutlets",
//       "paprika, for seasoning",
//       "1 lemon, halved"
//     ],
//     steps: [
//       "Heat oven to 190C/170C fan/gas 5. Halve the aubergines lengthways and score the flesh side deeply, brush with a good layer of olive oil and put on a baking sheet. Roast for 20 mins or until the flesh is soft enough to scoop out.",
//       "Fry the onion in a little oil until soft, add the garlic and cinnamon and fry for 1 min. Once the aubergines are cool enough to handle, scoop out the centres. Roughly chop the flesh and add it to the onions. Halve the tomatoes, scoop the seeds and juice into a sieve set over a bowl, then chop the flesh. Add the chopped tomatoes to the pan and cook everything for 10 mins until nice and soft. Add a little more oil if you need to. Stir in the parsley, leaving a little for scattering at the end.",
//       "Lay the aubergine halves in a baking dish and divide the tomato mixture between them. Pour over the juice from the tomatoes, drizzle with more olive oil and bake for 30 mins until the aubergines have collapsed.",
//       "Meanwhile, mix the tzatziki ingredients together and put in a small serving bowl.",
//       "Season the lamb with salt, black pepper and a pinch of paprika. Griddle, grill or barbecue for 3 mins on each side or until the fat is nicely browned, then put in a serving dish and squeeze over the lemon halves. Scatter the aubergines with parsley, then serve with the lamb and tzatziki."
//     ]
//   },
//   // {
//   //   title: "Pasta",
//   //   description: "",
//   //   stars: 5,
//   //   comments: [
//   //     {
//   //       username: "",
//   //       comment: "",
//   //     },
//   //   ],
//   //   prep: "15 mins",
//   //   time: "1 hr and 30 mins",
//   //   difficulity: "Easy",
//   //   sesrves: 6,
//   //   nutrition: {
//   //     kcal: 1,
//   //     fat: 1,
//   //     saturates: 1,
//   //     carbs: 1,
//   //     sugars: 1,
//   //     fibre: 1,
//   //     protein: 1,
//   //     salt: 1,
//   //   },
//   //   ingredients: [
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //   ],
//   //   steps: [
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //   ]
//   // },
//   // {
//   //   title: "Pasta",
//   //   description: "",
//   //   stars: 5,
//   //   comments: [
//   //     {
//   //       username: "",
//   //       comment: "",
//   //     },
//   //   ],
//   //   prep: "15 mins",
//   //   time: "1 hr and 30 mins",
//   //   difficulity: "Easy",
//   //   sesrves: 6,
//   //   nutrition: {
//   //     kcal: 1,
//   //     fat: 1,
//   //     saturates: 1,
//   //     carbs: 1,
//   //     sugars: 1,
//   //     fibre: 1,
//   //     protein: 1,
//   //     salt: 1,
//   //   },
//   //   ingredients: [
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //   ],
//   //   steps: [
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //   ]
//   // },
//   // {
//   //   title: "Pasta",
//   //   description: "",
//   //   stars: 5,
//   //   comments: [
//   //     {
//   //       username: "",
//   //       comment: "",
//   //     },
//   //   ],
//   //   prep: "15 mins",
//   //   time: "1 hr and 30 mins",
//   //   difficulity: "Easy",
//   //   sesrves: 6,
//   //   nutrition: {
//   //     kcal: 1,
//   //     fat: 1,
//   //     saturates: 1,
//   //     carbs: 1,
//   //     sugars: 1,
//   //     fibre: 1,
//   //     protein: 1,
//   //     salt: 1,
//   //   },
//   //   ingredients: [
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //   ],
//   //   steps: [
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //   ]
//   // },
//   // {
//   //   title: "Pasta",
//   //   description: "",
//   //   stars: 5,
//   //   comments: [
//   //     {
//   //       username: "",
//   //       comment: "",
//   //     },
//   //   ],
//   //   prep: "15 mins",
//   //   time: "1 hr and 30 mins",
//   //   difficulity: "Easy",
//   //   sesrves: 6,
//   //   nutrition: {
//   //     kcal: 1,
//   //     fat: 1,
//   //     saturates: 1,
//   //     carbs: 1,
//   //     sugars: 1,
//   //     fibre: 1,
//   //     protein: 1,
//   //     salt: 1,
//   //   },
//   //   ingredients: [
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //   ],
//   //   steps: [
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //     "",
//   //   ]
//   // },
// ];

